import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { TrpcProvider } from "~/utils/trpc-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  header,
  footer,
}: {
  children: React.ReactNode;
  header: React.ReactNode;
  footer: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TrpcProvider>
          <div className="flex min-h-screen">
            <div className="flex flex-col flex-grow">
              <header className="bg-gray-800 text-white p-4">{header}</header>
              <main className="flex-grow p-4">{children}</main>
              <footer className="bg-gray-800 text-white p-4">{footer}</footer>
            </div>
          </div>
        </TrpcProvider>
      </body>
    </html>
  );
}
